#!/usr/bin/env python3
""" MUST BE RUN IN PACKTAB REPO ROOT """

import sys
import json
sys.path.insert(0, 'Lib')

from packTab import pack_table, Code

with open('/Users/taj/repos/parley/composite_props.json', 'r') as f:
    data = json.load(f)

print(f"Loaded {len(data)} Unicode codepoint properties")

# Find the most common value to use as default
from collections import Counter
value_counts = Counter(data)
default = value_counts.most_common(1)[0][0]
default_count = value_counts[default]

print(f"Most common value: {default} (appears {default_count} times, {100*default_count/len(data):.2f}%)")
print(f"Unique values: {len(value_counts)}")
print()

print("Running packTab compression...")
print("This may take a moment for ~1.1M values...")

# Pack the table with compression level 1 (balanced)
solution = pack_table(data, default=default, compression=3)

print()
print("Compression results:")
print(f"  Uncompressed: {len(data) * 4} bytes (u32 array)")
print(f"  Compressed: {solution.cost} bytes")
print(f"  Compression ratio: {(len(data) * 4) / solution.cost:.2f}x")
print(f"  Lookups needed: {solution.nLookups}")
print(f"  Extra operations: {solution.nExtraOps}")
print()

print("Generating Rust code...")
code = Code("composite_props")
solution.genCode(code, "get", language="rust", private=False)

output_file = './composite_props_packtab.rs'
print(f"Writing to {output_file}...")

with open(output_file, 'w') as f:
    f.write("// Auto-generated by packTab\n")
    f.write("// Unicode composite properties lookup table\n")
    f.write("//\n")
    f.write(f"// Original size: {len(data)} u32 values = {len(data) * 4} bytes\n")
    f.write(f"// Compressed size: {solution.cost} bytes\n")
    f.write(f"// Compression ratio: {(len(data) * 4) / solution.cost:.2f}x\n")
    f.write(f"// Lookups: {solution.nLookups}, Extra ops: {solution.nExtraOps}\n")
    f.write("//\n")
    f.write(f"// Default value: {default}\n")
    f.write("//\n")
    f.write("// Usage: composite_props_get(codepoint as usize) -> u32\n")
    f.write("\n")
    
    # Redirect print to file
    code.print_code(file=f, language="rust", private=False)

print(f"✓ Successfully generated {output_file}")
print()
print("Summary:")
print(f"  Input: {len(data):,} codepoints")
print(f"  Output: {solution.cost:,} bytes")
print(f"  Savings: {len(data) * 4 - solution.cost:,} bytes")
print(f"  Space efficiency: {100 * solution.cost / (len(data) * 4):.2f}% of original")